### ISSUE TITLE
Support for JsonConverter

### ISSUE THREAD

**Issue by imclint21** [nenoNaninu/Tapper#114]
Hi,

Let imagine I have a property that return a list of objects, but I use a `JsonConverter` for reformat it, how it can be handled with Tapper?

Regards

**Comment by nenoNaninu** [comment]
Is it a use case such as mapping C#'s `int[]` to another user-defined type instead of TypeScript's `number[]`? We do not assume such a use case, and no feature supports it.

**Comment by imclint21** [comment]
Got it, just usually when you want to store a collection of strings using entity framework, you have to create a class instead of string but in API response you might want only the array of string.

**Comment by nenoNaninu** [comment]
Tapepr has no plans to support a custom JsonConverter. Because JsonConverter is extremely flexible, static-type constraints are difficult. 

Separating types used for DB and types transpiled to TypeScript is recommended.

```cs
class TypeForDb
{
    public string? Content { get; set; }
}

class TypeForWebApi
{
    public string[]? Content { get; set; }
}

static class Extensions
{
    public static TypeForDb ToTypeForDb (this TypeForWebApi source)
    {
        // impl
    }

    public static TypeForWebApi ToTypeForWebApi (this TypeForDb source)
    {
        // impl
    }
}
```
