### ISSUE TITLE
Handle `JsonConvert`

### ISSUE THREAD

**Issue by imclint21** [nenoNaninu/Tapper#124]
Hi,

Would be nice to have an handling of `JsonConvert` just maybe with a comment or an attribute, something for define :

```csharp
[JsonConverter(typeof(AuthorizedIpsConverter))]
public virtual ICollection<AuthorizedIp>? AuthorizedIps { get; set; }
```

Regards

**Comment by nenoNaninu** [comment]
No plans to support it. 
See https://github.com/nenoNaninu/Tapper/issues/114#issuecomment-1691834440
