### ISSUE TITLE
ARM support?

### ISSUE THREAD

**Issue by imclint21** [nenoNaninu/Tapper#204]
Hi,

Seems not work from a raspberry.

You must install .NET to run this application.

App: /root/.dotnet/tools/tapper
Architecture: arm64
App host version: 8.0.7
.NET location: Not found

Learn more:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:

**Comment by nenoNaninu** [comment]
> .NET location: Not found

It's not a Tapper's problem.
Make sure that other dotnet tools besides Tapper are working correctly.

**Comment by nenoNaninu** [comment]
Tapper is working correctly on Apple M1 (ARM). Your problem is not Tapper's problem.
