### ISSUE TITLE
[feedback] This library cannot be used in production code in multiple cases

### ISSUE THREAD

**Issue by 0xF6** [nenoNaninu/Tapper#234]
1. Every time need TranspilationSource (really, why can't you just go deep and pick up all types according to graph?)
2. TranspilationSource is not supported interfaces, really? (in Reinforced.Typings outofbox)
3. TranspilationSource cannot be use with generics (maybe not very important, but in cases Maybe or Either is so critical)
4. Cannot define type-converter for system types (eg system.drawing.color or etc external model) 

I probably won't use this library for these reasons, but I decided to write a feedback why I couldn't use your library in the project, I hope it will be useful 
(and yes, "issue", discussions is a disable in this repo)

**Comment by nenoNaninu** [comment]
>1. Every time need TranspilationSource (really, why can't you just go deep and pick up all types according to graph?)

**This is design. Explicit is better than implicit.**

It is easy to determine the transpile type implicitly from the dependency graph without annotating all transpiled types with attributes. However, this is not a good approach.

For hobbyists, implicit may be easier. However, this project is assumed to be used not only in the hobby but also in production.
When used in production, it is undesirable to determine the type to be transpiled implicitly. Also, if everything has an attribute, it will be obvious at a glance that it will be the target of a Tapper's transpile, and the engineer will be cautious about changing it.

The reason why Tapper provides an analyzer is to make it easier to specify attributes explicitly. If I had decided to allow implicit transpiling, I would not have included the analyzer in the first place. Explicit is better than implicit.

In addition, it is a common practice in various libraries to attach attributes to all types of something. For example, MessagePack and protobuf-net attach attributes to all types to be serialized. Such methods are widely used and accepted.

>2. TranspilationSource is not supported interfaces, really? (in Reinforced.Typings outofbox)

**There is room for consideration, but it is unnecessary at this point.**

With the exception of some types, such as collection types, you must add `[JsonDerivedType]` to correctly serialize/deserialize C # interfaces. Unless you add `[TranspilationSource]` to all derived types, you cannot correctly handle derived types in TypeScript.

From this, how necessary is it to add `[TranspilationSource]` to C# interfaces? Also, given that `[JsonDerivedType]` specifies all the expected derived types, annotating `[TranspilationSource]` is not a big deal.

Furthermore, when communicating between C# and TypeScript, POCO is more common than interfaces, although communication between C# and C# may be a different story.

```cs
[JsonDerivedType(typeof(Fuga), typeDiscriminator: nameof(Fuga))]
[JsonDerivedType(typeof(Piyo), typeDiscriminator: nameof(Piyo))]
public interface IHoge
{
    public int Value { get; set; }
}

public class Fuga : IHoge
{
    public int Value { get; set; }
    public int Value2 { get; set; }
}

public class Piyo : IHoge
{
    public int Value { get; set; }
    public int Value3 { get; set; }
}
```

>3. TranspilationSource cannot be use with generics (maybe not very important, but in cases Maybe or Either is so critical)

**Not necessarily required.**

There are no generics in protocol buffers. I may support them in the future, but for now they are also unnecessary in Tapper.

>4. Cannot define type-converter for system types (eg system.drawing.color or etc external model)

**Wrap it yourself.**
