### ISSUE TITLE
Need an exclude attribute

### ISSUE THREAD

**Issue by thisisclint21** [nenoNaninu/Tapper#69]
Hey,

I think it would be great to be able to exclude some properties.

Regards

**Comment by nenoNaninu** [comment]
I am thinking of adding a feature in the next version that would allow the serializer attributes (like `[JsonIgnore]`) to affect the generated TypeScript code. I think this will satisfy the demand. (Related:  #72)

**Comment by thisisclint21** [comment]
That would be awesome! :D

**Comment by nenoNaninu** [comment]
Support from v1.8.0
https://github.com/nenoNaninu/Tapper/releases/tag/v1.8.0

**Comment by imclint21** [comment]
What about `[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]` ?

**Comment by nenoNaninu** [comment]
Currently not supported.
