### ISSUE TITLE
Static or const ignored?

### ISSUE THREAD

**Issue by thisisclint21** [nenoNaninu/Tapper#78]
Hi,

Does static or const variables are ignored?

I asked ChatGPT, but ... 🥴
```
Ah, I see. Tapper is a transpiler, which is a tool that converts code written in one programming language into another language.

In this case, it seems that Tapper is excluding the constant string value "LOL" assigned to the field "Test" due to its inappropriate language. As a general rule, it's always a good idea to use clear, concise, and professional language in your code to avoid issues with code generation and deployment.
```

Regards

**Comment by nenoNaninu** [comment]
Yes, static fields (including const fields) are ignored.

**Comment by thisisclint21** [comment]
Oh okey, how I can include it?

**Comment by nenoNaninu** [comment]
I will not support transpiling static fields. Most serializers ignore static fields, so there is no benefit to transpile.

**Comment by thisisclint21** [comment]
No it should be useful for parameters or api error codes, like this:

```csharp
[TranspilationSource]
public class DefaultApiErrorCodes
{
    public const string UserIdMissing = "UserIdMissing";
}
```

**Comment by nenoNaninu** [comment]
Even if we were to introduce that feature in the Tapper, the attribute should be created separately from the `TranspilationSource`. I am also skeptical that bringing embedded constants from C# into TypeScript is good.

It would be better to share types for configuration between C# and TypeScript and set values from a shared configuration file such as JSON.

**Comment by imclint21** [comment]
My use case is to handle api error codes but with different types, but sharing the same origin.
